version: '3.8'

services:
  # Next.js web application
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PYTHON_SERVICE_URL=http://python-service:8000
    depends_on:
      - python-service
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - app-network

  # Python document chunking service
  python-service:
    build: ./python-service
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./python-service:/app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
    driver: local
